### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by WesselSmit** [Wiebsonice/frontend-data#1]
Wiebe heeft zijn vorige readme van **frontend-applications** copy/pasted, de content moet voor een groot gedeelte dus nog aangepast worden.

# Wat moet er nog gedaan worden?
- [ ] files zoals `.gitignore` `.gitattributes` in de `.gitignore` zetten
- [x] add live link
- [x] add repository description 
- [x] assignment description (heeft nog oude inhoud)
- [x]  image (heeft nog oude inhoud)
- [x] geef aan welke data je gebruikt (heeft nog oude content)
     - [x] geef aan wat je doet met lege/lage/hoge waardes
- [x] updated pattern documenteren
- [x] functional cleaning/transforming pattern

_Concept kan nog niet beoordeeld worden_

# Voorgestelde verbeteringen? 
* maak de voorbeeld link duidelijker/prominenter
* acknowledgements mogen wel iets uitgebreider
* hierbij kan je denk beter gebruik maken van een regex die alle alphabetical chars checkt?
```javascript
 var replaceArr = ["a","b","c","d","e","f","g","h","i","j","k","l","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z", /\(/, /\)/, /\./, , /\?/]
        replaceArr.forEach(el => data.value = data.value.replace(new RegExp(el, "g"), ""))
```
* je zou modules kunnen gebruiken voor wat meer overzicht

# Wat is er erg goed?
- [x] Code is goed functional, voorzien van meaningful comments & gebruikt goede naming conventions

**Comment by Wiebsonice** [comment]
Re. de gitignore, het is niet best practice om je gitignore the girignoren.

Re de regex, Deze vorm van regex is veel dynamischer om te gebruiken
